# 仅 build 时使用：含 build-std + json-target-spec，供 PvmBuilder 内层 cargo 读取
[build]
target = "riscv64emac-unknown-none-polkavm.json"

[unstable]
build-std = ["core", "alloc"]
json-target-spec = true

[env]
RUSTC_BOOTSTRAP = "1"
