[workspace]
members = [
    "crates/wrevive-macro",
    "crates/wrevive-api",
    "examples/wrevive-example-contract",
    "examples/flipper",
    "examples/incrementer",
    "examples/fallible-setter",
    "examples/trait-incrementer",
    "examples/erc721",
    "examples/simple-storage",
    "examples/dns",
]
resolver = "2"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

[profile.dev]
opt-level = 0
debug = true
