[package]
name = "erc721"
version = "0.1.0"
edition = "2021"
description = "ink 风格 ERC721 简化版：mint/balance_of/owner_of/transfer，对应 ink erc721"

[features]
default = []

[lib]
name = "erc721"
crate-type = ["cdylib"]

[build-dependencies]
polkavm-linker = "0.30"

[dependencies]
wrevive-macro = { path = "../../crates/wrevive-macro" }
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["on_chain"] }

[dev-dependencies]
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["off_chain"] }
