[package]
name = "wrevive-delegate"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "wrevive-delegate"
path = "src/contract.rs"

[dependencies]
pvm-bump-allocator = { workspace = true }
polkavm-derive = { workspace = true }
alloy-core = { workspace = true }
pallet-revive-uapi = { workspace = true }
parity-scale-codec = { workspace = true }
pvm-contract-types = { workspace = true }
wrevive-macro = { path = "../../crates/wrevive-macro" }
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["on_chain"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
overflow-checks = false

[dev-dependencies]
blake2 = { workspace = true }
digest = { workspace = true }
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["off_chain"] }