[package]
name = "incrementer"
version = "0.1.0"
edition = "2021"
description = "ink 风格 Incrementer 示例：i32 计数器 inc/get，对应 ink/integration-tests/public/incrementer"

[features]
default = []

[lib]
name = "incrementer"
crate-type = ["cdylib"]

[build-dependencies]
polkavm-linker = "0.30"

[dependencies]
wrevive-macro = { path = "../../crates/wrevive-macro" }
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["on_chain"] }

[dev-dependencies]
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["off_chain"] }
