[package]
name = "dns"
version = "0.1.0"
edition = "2021"
description = "域名解析简化版：register/set_address/get_address/get_owner，对应 ink dns"

[features]
default = []

[lib]
name = "dns"
crate-type = ["cdylib"]

[build-dependencies]
polkavm-linker = "0.30"

[dependencies]
wrevive-macro = { path = "../../crates/wrevive-macro" }
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["on_chain"] }

[dev-dependencies]
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["off_chain"] }
