[package]
name = "wrevive-codec-contract"
version = "0.1.0"
edition = "2024"
description = "示例合约：value/owner 存储与 message，供 PolkaVM 部署"

[[bin]]
name = "wrevive-codec"
path = "src/contract.rs"

[dependencies]
pvm-bump-allocator = { git = "https://github.com/paritytech/cargo-pvm-contract", branch = "main" }
polkavm-derive = "0.31"
alloy-core = { version = "1.5", default-features = false, features = ["sol-types"] }
pallet-revive-uapi = { version = "0.10", default-features = false }
parity-scale-codec = { version = "3", default-features = false, features = ["derive"] }
wrevive-macro = { path = "../../crates/wrevive-macro" }
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["on_chain"] }

[profile.release]
codegen-units = 1
lto = true
opt-level = "z"
panic = "abort"
overflow-checks = false

[dev-dependencies]
wrevive-api = { path = "../../crates/wrevive-api", default-features = false, features = ["off_chain"] }